# file version 0.1 fo4
import subprocess
import os

try:
    from settings import *
except ImportError:
    print("settings.py not found. creating...")
    with open("settings.py", "w") as f:
        f.write("""
#DO NOT EDIT THIS ENTRY
#This file is automatically generated by the cleaner.
#if this entry is edited, the cleaner will rewirite the entiere settings.py file
fileversion = "0.1"


#path to Fallout 4 root directory
#default: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4
# hint do not use "\\" in the path ... use \\\\ instead
path = "E:\\\\SteamLibrary\\\\steamapps\\\\common\\\\Fallout 4"

#data directory
#default: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data
# or short: path + "\\\\Data"
# use \\\\ instead of "\\"
data = path + "\\Data"


# in this files are the files that need to be copied / cleaned stored as a list
# example for sse:
# master_list = "master_list.txt" > ["Skyrim.esm", "Update.esm", "HearthFires.esm", "Dragonborn.esm", "Dawnguard.esm"]
# clean_list = "clean_list.txt" > [ "Update.esm", "HearthFires.esm", "Dragonborn.esm", "Dawnguard.esm"]
master_list = "masterlist.txt"
clean_list = "clean_masterlist.txt"


# path to F04Edit
# use \\\\ instead of "\\"
# path + executable file name (c:\\.....\\F04Edit.exe)
xedit = "C:\\\\Program Files (x86)\\\\FO4Edit\\\\FO4Edit.exe"

""")
    print("settings.py created. please edit it and run the script again.")
    exit()
CopyFileList = []
CleanFileList = []



def loadTxt():
    global CleanFileList
    with open(clean_list, "r") as file:
        for line in file:
            CleanFileList.append(line.strip())


def SSEEDIT():
    global data, xedit
    for ESMFile in CleanFileList:
        print("cleaning "+ESMFile+"...")
        args = f'{xedit} -quickautoclean -autoexit -autoload "{ESMFile}" -D:{data}'
        print(args)
        subprocess.call(args, shell=False)


def cleanNames(CleanFileList):
    x = []
    for ESMFile in CleanFileList:
        if ESMFile.find(" ") != -1:
          x.append(f'\"{ESMFile}\"')
        else:
          x.append(ESMFile)
    return x


if __name__ == '__main__':
    loadTxt()
    print(CleanFileList)
    print(path)

    CleanFileList = cleanNames(CleanFileList)
    print(CleanFileList)

    SSEEDIT()
